export const languages = {
  en: {
    name: 'English',
    emoji: '🇺🇸',
    translation: {
      welcome: "Hello! I'm **Myralis AI**. How can I help you today?",
      placeholder: "Ask Myralis anything...",
      send: "Send",
      listening: "Listening...",
      settings: "Settings",
      clearChat: "Clear Chat",
      export: "Export",
      search: "Search chat...",
      darkMode: "Dark Mode",
      autoSpeak: "Auto Speak",
      systemPrompt: "System Prompt",
      editPrompt: "Edit System Prompt",
      savePrompt: "Save Prompt",
      resetPrompt: "Reset Default",
      stats: "Show Stats",
      pinned: "Pinned",
      edited: "Edited",
      copy: "Copy message",
      regenerate: "Regenerate",
      pin: "Pin message",
      unpin: "Unpin message",
      error: "Error: ",
      connectionError: "Connection error. Please try again.",
      analyzing: "Analyzing...",
      thinking: "Myralis is thinking...",
      startListening: "Start listening",
      stopListening: "Stop listening",
      uploadImage: "Upload image",
      liveVision: "Live Vision",
      stopLive: "Stop Live Vision",
      cameraReady: "Camera ready",
      analyzingFrame: "Analyzing frame...",
      couldNotAnalyze: "Could not analyze this frame.",
      analysisFailed: "Analysis failed. Trying again...",
      chatExport: "Chat Export",
      exported: "Exported",
      messages: "messages",
      words: "words",
      context: "Context",
      memory: "Memory",
      responseTime: "Response Time",
      quickActions: "Quick Actions",
      summarize: "Summarize",
      brainstorm: "Brainstorm",
      explain: "Explain",
      teach: "Teach"
    }
  },
  es: {
    name: 'Español',
    emoji: '🇪🇸',
    translation: {
      welcome: "¡Hola! Soy **Myralis AI**. ¿Cómo puedo ayudarte hoy?",
      placeholder: "Pregunta a Myralis cualquier cosa...",
      send: "Enviar",
      listening: "Escuchando...",
      settings: "Configuración",
      clearChat: "Borrar Chat",
      export: "Exportar",
      search: "Buscar en el chat...",
      darkMode: "Modo Oscuro",
      autoSpeak: "Auto Hablar",
      systemPrompt: "Prompt del Sistema",
      editPrompt: "Editar Prompt del Sistema",
      savePrompt: "Guardar Prompt",
      resetPrompt: "Restablecer Predeterminado",
      stats: "Mostrar Estadísticas",
      pinned: "Fijado",
      edited: "Editado",
      copy: "Copiar mensaje",
      regenerate: "Regenerar",
      pin: "Fijar mensaje",
      unpin: "Desfijar mensaje",
      error: "Error: ",
      connectionError: "Error de conexión. Por favor, inténtalo de nuevo.",
      analyzing: "Analizando...",
      thinking: "Myralis está pensando...",
      startListening: "Comenzar a escuchar",
      stopListening: "Dejar de escuchar",
      uploadImage: "Subir imagen",
      liveVision: "Visión en Vivo",
      stopLive: "Detener Visión en Vivo",
      cameraReady: "Cámara lista",
      analyzingFrame: "Analizando cuadro...",
      couldNotAnalyze: "No se pudo analizar este cuadro.",
      analysisFailed: "El análisis falló. Intentando de nuevo...",
      chatExport: "Exportar Chat",
      exported: "Exportado",
      messages: "mensajes",
      words: "palabras",
      context: "Contexto",
      memory: "Memoria",
      responseTime: "Tiempo de Respuesta",
      quickActions: "Acciones Rápidas",
      summarize: "Resumir",
      brainstorm: "Lluvia de Ideas",
      explain: "Explicar",
      teach: "Enseñar"
    }
  },
  zh: {
    name: '中文',
    emoji: '🇨🇳',
    translation: {
      welcome: "你好！我是 **Myralis AI**。今天我能帮你什么？",
      placeholder: "向 Myralis 提问...",
      send: "发送",
      listening: "正在听...",
      settings: "设置",
      clearChat: "清除聊天",
      export: "导出",
      search: "搜索聊天...",
      darkMode: "暗黑模式",
      autoSpeak: "自动朗读",
      systemPrompt: "系统提示",
      editPrompt: "编辑系统提示",
      savePrompt: "保存提示",
      resetPrompt: "重置默认",
      stats: "显示统计",
      pinned: "已固定",
      edited: "已编辑",
      copy: "复制消息",
      regenerate: "重新生成",
      pin: "固定消息",
      unpin: "取消固定",
      error: "错误：",
      connectionError: "连接错误。请重试。",
      analyzing: "分析中...",
      thinking: "Myralis 正在思考...",
      startListening: "开始收听",
      stopListening: "停止收听",
      uploadImage: "上传图片",
      liveVision: "实时视觉",
      stopLive: "停止实时视觉",
      cameraReady: "相机已就绪",
      analyzingFrame: "正在分析画面...",
      couldNotAnalyze: "无法分析此画面。",
      analysisFailed: "分析失败。正在重试...",
      chatExport: "聊天导出",
      exported: "已导出",
      messages: "消息",
      words: "词数",
      context: "上下文",
      memory: "记忆",
      responseTime: "响应时间",
      quickActions: "快捷操作",
      summarize: "总结",
      brainstorm: "头脑风暴",
      explain: "解释",
      teach: "教学"
    }
  },
  hi: {
    name: 'हिंदी',
    emoji: '🇮🇳',
    translation: {
      welcome: "नमस्ते! मैं **Myralis AI** हूँ। आज मैं आपकी कैसे मदद कर सकता हूँ?",
      placeholder: "Myralis से कुछ भी पूछें...",
      send: "भेजें",
      listening: "सुन रहा हूँ...",
      settings: "सेटिंग्स",
      clearChat: "चैट साफ़ करें",
      export: "निर्यात करें",
      search: "चैट खोजें...",
      darkMode: "डार्क मोड",
      autoSpeak: "ऑटो बोलें",
      systemPrompt: "सिस्टम प्रॉम्प्ट",
      editPrompt: "सिस्टम प्रॉम्प्ट संपादित करें",
      savePrompt: "प्रॉम्प्ट सहेजें",
      resetPrompt: "डिफ़ॉल्ट रीसेट करें",
      stats: "आँकड़े दिखाएँ",
      pinned: "पिन किया गया",
      edited: "संपादित किया गया",
      copy: "संदेश कॉपी करें",
      regenerate: "पुनर्जनन",
      pin: "संदेश पिन करें",
      unpin: "संदेश अनपिन करें",
      error: "त्रुटि: ",
      connectionError: "कनेक्शन त्रुटि। कृपया पुनः प्रयास करें।",
      analyzing: "विश्लेषण कर रहा हूँ...",
      thinking: "Myralis सोच रहा है...",
      startListening: "सुनना शुरू करें",
      stopListening: "सुनना बंद करें",
      uploadImage: "छवि अपलोड करें",
      liveVision: "लाइव विजन",
      stopLive: "लाइव विजन बंद करें",
      cameraReady: "कैमरा तैयार",
      analyzingFrame: "फ्रेम का विश्लेषण कर रहा हूँ...",
      couldNotAnalyze: "इस फ्रेम का विश्लेषण नहीं कर सका।",
      analysisFailed: "विश्लेषण विफल। पुनः प्रयास कर रहा हूँ...",
      chatExport: "चैट निर्यात",
      exported: "निर्यात किया गया",
      messages: "संदेश",
      words: "शब्द",
      context: "संदर्भ",
      memory: "स्मृति",
      responseTime: "प्रतिक्रिया समय",
      quickActions: "त्वरित क्रियाएँ",
      summarize: "सारांश",
      brainstorm: "विचार-मंथन",
      explain: "समझाएँ",
      teach: "सिखाएँ"
    }
  },
  fr: {
    name: 'Français',
    emoji: '🇫🇷',
    translation: {
      welcome: "Bonjour ! Je suis **Myralis AI**. Comment puis-je vous aider aujourd'hui ?",
      placeholder: "Demandez à Myralis n'importe quoi...",
      send: "Envoyer",
      listening: "Écoute...",
      settings: "Paramètres",
      clearChat: "Effacer la discussion",
      export: "Exporter",
      search: "Rechercher dans la discussion...",
      darkMode: "Mode Sombre",
      autoSpeak: "Parole Automatique",
      systemPrompt: "Invite Système",
      editPrompt: "Modifier l'Invite Système",
      savePrompt: "Enregistrer l'Invite",
      resetPrompt: "Réinitialiser par Défaut",
      stats: "Afficher les Statistiques",
      pinned: "Épinglé",
      edited: "Modifié",
      copy: "Copier le message",
      regenerate: "Régénérer",
      pin: "Épingler le message",
      unpin: "Désépingler le message",
      error: "Erreur : ",
      connectionError: "Erreur de connexion. Veuillez réessayer.",
      analyzing: "Analyse en cours...",
      thinking: "Myralis réfléchit...",
      startListening: "Commencer à écouter",
      stopListening: "Arrêter d'écouter",
      uploadImage: "Télécharger une image",
      liveVision: "Vision en Direct",
      stopLive: "Arrêter la Vision en Direct",
      cameraReady: "Caméra prête",
      analyzingFrame: "Analyse du cadre...",
      couldNotAnalyze: "Impossible d'analyser ce cadre.",
      analysisFailed: "L'analyse a échoué. Nouvel essai...",
      chatExport: "Exporter la Discussion",
      exported: "Exporté",
      messages: "messages",
      words: "mots",
      context: "Contexte",
      memory: "Mémoire",
      responseTime: "Temps de Réponse",
      quickActions: "Actions Rapides",
      summarize: "Résumer",
      brainstorm: "Remue-méninges",
      explain: "Expliquer",
      teach: "Enseigner"
    }
  },
  ja: {
    name: '日本語',
    emoji: '🇯🇵',
    translation: {
      welcome: "こんにちは！私は **Myralis AI** です。今日はどのようにお手伝いしましょうか？",
      placeholder: "Myralisに何でも質問してください...",
      send: "送信",
      listening: "聴いています...",
      settings: "設定",
      clearChat: "チャットをクリア",
      export: "エクスポート",
      search: "チャットを検索...",
      darkMode: "ダークモード",
      autoSpeak: "自動音声",
      systemPrompt: "システムプロンプト",
      editPrompt: "システムプロンプトを編集",
      savePrompt: "プロンプトを保存",
      resetPrompt: "デフォルトにリセット",
      stats: "統計を表示",
      pinned: "ピン留め",
      edited: "編集済み",
      copy: "メッセージをコピー",
      regenerate: "再生成",
      pin: "メッセージをピン留め",
      unpin: "ピン留めを解除",
      error: "エラー：",
      connectionError: "接続エラー。もう一度お試しください。",
      analyzing: "分析中...",
      thinking: "Myralisは考え中です...",
      startListening: "音声入力を開始",
      stopListening: "音声入力を停止",
      uploadImage: "画像をアップロード",
      liveVision: "ライブビジョン",
      stopLive: "ライブビジョンを停止",
      cameraReady: "カメラ準備完了",
      analyzingFrame: "フレームを分析中...",
      couldNotAnalyze: "このフレームを分析できませんでした。",
      analysisFailed: "分析に失敗しました。再試行中...",
      chatExport: "チャットをエクスポート",
      exported: "エクスポート完了",
      messages: "メッセージ",
      words: "単語数",
      context: "コンテキスト",
      memory: "メモリ",
      responseTime: "応答時間",
      quickActions: "クイックアクション",
      summarize: "要約",
      brainstorm: "ブレインストーミング",
      explain: "説明",
      teach: "教える"
    }
  },
  de: {
    name: 'Deutsch',
    emoji: '🇩🇪',
    translation: {
      welcome: "Hallo! Ich bin **Myralis AI**. Wie kann ich Ihnen heute helfen?",
      placeholder: "Fragen Sie Myralis alles...",
      send: "Senden",
      listening: "Höre zu...",
      settings: "Einstellungen",
      clearChat: "Chat löschen",
      export: "Exportieren",
      search: "Chat durchsuchen...",
      darkMode: "Dunkelmodus",
      autoSpeak: "Automatisch Sprechen",
      systemPrompt: "Systemaufforderung",
      editPrompt: "Systemaufforderung bearbeiten",
      savePrompt: "Aufforderung speichern",
      resetPrompt: "Standard wiederherstellen",
      stats: "Statistiken anzeigen",
      pinned: "Angepinnt",
      edited: "Bearbeitet",
      copy: "Nachricht kopieren",
      regenerate: "Neu generieren",
      pin: "Nachricht anpinnen",
      unpin: "Nachricht lösen",
      error: "Fehler: ",
      connectionError: "Verbindungsfehler. Bitte versuchen Sie es erneut.",
      analyzing: "Analysiere...",
      thinking: "Myralis denkt nach...",
      startListening: "Spracherkennung starten",
      stopListening: "Spracherkennung stoppen",
      uploadImage: "Bild hochladen",
      liveVision: "Live-Vision",
      stopLive: "Live-Vision stoppen",
      cameraReady: "Kamera bereit",
      analyzingFrame: "Frame analysieren...",
      couldNotAnalyze: "Dieser Frame konnte nicht analysiert werden.",
      analysisFailed: "Analyse fehlgeschlagen. Neuer Versuch...",
      chatExport: "Chat exportieren",
      exported: "Exportiert",
      messages: "Nachrichten",
      words: "Wörter",
      context: "Kontext",
      memory: "Speicher",
      responseTime: "Antwortzeit",
      quickActions: "Schnellaktionen",
      summarize: "Zusammenfassen",
      brainstorm: "Brainstorming",
      explain: "Erklären",
      teach: "Lehren"
    }
  }
};

export const getTranslation = (lang, key) => {
  return languages[lang]?.translation[key] || languages['en'].translation[key] || key;
};
